name: Secret Scan (diff)
on:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for common secrets
        run: |
          set -e
          rg -n --pcre2 "(AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35}|ssh-rsa AAAA|-----BEGIN (RSA|EC) PRIVATE KEY-----)" || true
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "::error::Potential secret detected in diff"; exit 1; 
          fi
